
### requestDOCK

POST http://localhost:8080/registrations
Content-Type: application/json

{"productId": 801,"attendeeName": "Tzouliano Giazai"}

###requestDOCK2
POST http://localhost:8080/registrations
Content-Type: application/json

{"productId": 802,"attendeeName": "John Smith"}